"""split shipping address

Revision ID: c6bdd16e5e70
Revises: 7ba1954db105
Create Date: 2026-05-27 09:42:54.837677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6bdd16e5e70'
down_revision: Union[str, Sequence[str], None] = '7ba1954db105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('street', sa.String(), server_default='Ekwueme Street', nullable=False))
    op.add_column('orders', sa.Column('city', sa.String(), server_default='Ikorodu', nullable=False))
    op.add_column('orders', sa.Column('lga', sa.String(), server_default='Ikorodu', nullable=False))
    op.add_column('orders', sa.Column('state', sa.String(), server_default='Lagos', nullable=False))
    op.add_column('orders', sa.Column('country', sa.String(), server_default='Nigeria', nullable=False))
    op.drop_column('orders', 'shipping_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipping_address', sa.VARCHAR(), server_default=sa.text("'firebender'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('orders', 'country')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'lga')
    op.drop_column('orders', 'street')
    # ### end Alembic commands ###
